### ISSUE TITLE
Bad asset pool 'pengrandomspear'

### ISSUE THREAD

**Issue by evonzee** [evonzee/grayles-modpack-updater#10]
[Error] Could not instantiate item '[pengrandomspear, 1, {}]'. (LuaException) Error code 2, [string "/scripts/util.lua"]:580: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in ?
        [C]: in function '_ENV.pairs'
        [string "/scripts/util.lua"]:580: in field 'mergeTable'
        [string "/items/buildscripts/buildweapon.lua"]:55: in function <[string "/items/buildscripts/buildweapon.lua"]:7>

**Comment by evonzee** [comment]
This looks like it is happening because pengrandomspear has a chance to include the elementalAura and elementalPillar abilities even though it may not be an elemental weapon ("physical" elemental type).  These abilities require an elemental damage type to be present on the weapon since they have no configuration for "physical".  

I can fix this by dropping physical as a damage type option, dropping those abilities from the pool, or patching support for physical damage (nonsensical though it may be) into those abilities.  Preference?

**Comment by evonzee** [comment]
Umbra's choice is teh physical aura and pillar.  Patched, let's see how it works.

**Comment by Umbralink** [comment]
It only a fix for now until the author decide to fix it himself, we may do as we wish. :)
